import os
import re
import json
import py_compile
from datetime import datetime
from typing import Dict, Any, List, Optional
from core.subagent import BaseSubAgent

AI_TRACE_PATTERNS = [
    r"#\s*(AI generated|Generated by AI|Auto-generated by AI|Created by AI assistant).*",
    r"//\s*(AI generated|Generated by AI|Auto-generated by AI|Created by AI assistant).*",
    r"<!--\s*(AI generated|Generated by AI|Auto-generated by AI|Created by AI assistant)\s*-->",
    r"/\*\s*(AI generated|Generated by AI|Auto-generated by AI)\s*\*/",
    r"#\s*TODO:\s*(AI|Gemini|Claude|Copilot).*",
    r"//\s*TODO:\s*(AI|Gemini|Claude|Copilot).*"
]

class SpecAlignmentCheckerSubAgent(BaseSubAgent):
    """
    Subagent 1: Audits codebase for brand inconsistencies and outdated presentation stats.
    """
    def __init__(self):
        super().__init__(
            subagent_id="spec_alignment_checker",
            name="Spec Alignment Checker SubAgent",
            parent_agent_id="spec_auditor",
            description="Scans source files for brand naming inconsistencies and outdated presentation deck copy."
        )

    def execute(self, payload: Dict[str, Any]) -> Dict[str, Any]:
        target_path = payload.get("target_path", "")
        canonical_brand = payload.get("canonical_brand", "Med360")
        disallowed_brands = payload.get("disallowed_brands", ["Medical 360 Ltd", "Medical360 Ltd"])

        findings = []
        files_scanned = 0
        base_dirs = [target_path] if os.path.exists(target_path) else [os.getcwd()]

        for base in base_dirs:
            for root, dirs, files in os.walk(base):
                dirs[:] = [d for d in dirs if d not in [".git", "node_modules", ".venv", "__pycache__", "venv", "backups"]]
                for file in files:
                    if not file.endswith((".html", ".js", ".css", ".py", ".json", ".md")):
                        continue
                    files_scanned += 1
                    filepath = os.path.join(root, file)
                    rel_path = os.path.relpath(filepath, base)
                    try:
                        with open(filepath, "r", encoding="utf-8", errors="ignore") as f:
                            content = f.read()

                        for bad in disallowed_brands:
                            if bad.lower() in content.lower():
                                findings.append({
                                    "file": rel_path,
                                    "type": "BRAND_INCONSISTENCY",
                                    "severity": "HIGH",
                                    "detail": f"Contains deprecated entity name '{bad}'. Must be '{canonical_brand}'."
                                })

                        if "1,200+ Patients" in content:
                            findings.append({
                                "file": rel_path,
                                "type": "OUTDATED_STAT",
                                "severity": "MEDIUM",
                                "detail": "Outdated stat '1,200+ Patients'. Presentation spec specifies '+3,000 Patients Assisted'."
                            })
                    except Exception:
                        pass

        return {
            "files_scanned": files_scanned,
            "discrepancies_count": len(findings),
            "findings": findings
        }


class AITracePurgeSubAgent(BaseSubAgent):
    """
    Subagent 2: Detects and strips robotic AI comments and boilerplate watermarks from codebase.
    """
    def __init__(self):
        super().__init__(
            subagent_id="spec_ai_trace_purger",
            name="AI Trace Purge SubAgent",
            parent_agent_id="spec_auditor",
            description="Sanitizes AI watermarks, robotic comments, and auto-generated boilerplate tags from source code."
        )

    def execute(self, payload: Dict[str, Any]) -> Dict[str, Any]:
        target_path = payload.get("target_path", "")
        dry_run = payload.get("dry_run", False)

        base_dirs = [target_path] if os.path.exists(target_path) else [os.getcwd()]
        cleaned_files = 0
        traces_detected = []

        for base in base_dirs:
            for root, dirs, files in os.walk(base):
                dirs[:] = [d for d in dirs if d not in [".git", "node_modules", ".venv", "__pycache__", "venv", "backups"]]
                for file in files:
                    if not file.endswith((".html", ".js", ".css", ".py")):
                        continue
                    filepath = os.path.join(root, file)
                    rel_path = os.path.relpath(filepath, base)
                    try:
                        with open(filepath, "r", encoding="utf-8", errors="ignore") as f:
                            content = f.read()

                        original_content = content
                        for pattern in AI_TRACE_PATTERNS:
                            matches = re.findall(pattern, content, re.IGNORECASE)
                            if matches:
                                traces_detected.append({"file": rel_path, "pattern": pattern, "count": len(matches)})
                                if not dry_run:
                                    content = re.sub(pattern, "", content, flags=re.IGNORECASE)

                        if not dry_run and content != original_content:
                            with open(filepath, "w", encoding="utf-8") as f:
                                f.write(content)
                            cleaned_files += 1
                    except Exception:
                        pass

        return {
            "traces_detected_count": len(traces_detected),
            "traces": traces_detected,
            "cleaned_files_count": cleaned_files,
            "dry_run": dry_run
        }


class BuildSafetyVerifierSubAgent(BaseSubAgent):
    """
    Subagent 3: Pre-push syntax and build integrity verifier.
    """
    def __init__(self):
        super().__init__(
            subagent_id="spec_build_safety_verifier",
            name="Build Safety Verifier SubAgent",
            parent_agent_id="spec_auditor",
            description="Performs syntax compilation checks on Python source files and verifies JSON validity."
        )

    def execute(self, payload: Dict[str, Any]) -> Dict[str, Any]:
        target_path = payload.get("target_path", "")
        base_dirs = [target_path] if os.path.exists(target_path) else [os.getcwd()]

        py_checked = 0
        json_checked = 0
        errors = []

        for base in base_dirs:
            for root, dirs, files in os.walk(base):
                dirs[:] = [d for d in dirs if d not in [".git", "node_modules", ".venv", "__pycache__", "venv", "backups"]]
                for file in files:
                    filepath = os.path.join(root, file)
                    rel_path = os.path.relpath(filepath, base)
                    
                    if file.endswith(".py"):
                        py_checked += 1
                        try:
                            py_compile.compile(filepath, doraise=True)
                        except Exception as e:
                            errors.append({"file": rel_path, "type": "PYTHON_SYNTAX_ERROR", "error": str(e)})

                    elif file.endswith(".json"):
                        json_checked += 1
                        try:
                            with open(filepath, "r", encoding="utf-8") as f:
                                json.load(f)
                        except Exception as e:
                            errors.append({"file": rel_path, "type": "JSON_SYNTAX_ERROR", "error": str(e)})

        is_healthy = len(errors) == 0
        return {
            "python_files_verified": py_checked,
            "json_files_verified": json_checked,
            "errors_found": len(errors),
            "errors": errors,
            "build_healthy": is_healthy
        }
